# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main","dex-xtf","dev-elastic" ]
  pull_request:
    branches: [ "main","dex-xtf","dev-elastic" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Prints the current branch
      run: echo "${GITHUB_REF##*/}"
    - name: Build with Ant
      run: ant -noinput -buildfile build-xtools.xml -Dfeature=${GITHUB_REF##*/}
